"""Added association table user_location

Revision ID: c71214994d1e
Revises: c40eb0e80ac1
Create Date: 2024-12-09 15:36:05.174029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71214994d1e'
down_revision: Union[str, None] = 'c40eb0e80ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_location',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'],"Location FK constraint" ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], "User FK constraint" ),
    sa.PrimaryKeyConstraint('user_id', 'location_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_location')
    # ### end Alembic commands ###
