"""Add AirPurifier model

Revision ID: 4bf7d5ef0cdc
Revises: c71214994d1e
Create Date: 2025-07-09 23:26:39.614140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf7d5ef0cdc'
down_revision: Union[str, None] = 'c71214994d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('air_quality', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('fan_speed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'fan_speed')
    op.drop_column('devices', 'air_quality')
    # ### end Alembic commands ###
