"""Added foreign key(location) in user table

Revision ID: 5641bec18bc1
Revises: a7c247740913
Create Date: 2024-12-08 15:59:27.181402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5641bec18bc1'
down_revision: Union[str, None] = 'a7c247740913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'locations', ['location_id'], ['location_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'location_id')
    # ### end Alembic commands ###
