"""Added column size in table devices

Revision ID: 65d4d21751c8
Revises: d985bdb9d674
Create Date: 2024-12-08 15:53:05.455930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d4d21751c8'
down_revision: Union[str, None] = 'd985bdb9d674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'size')
    # ### end Alembic commands ###
