"""Removed column size in table devices

Revision ID: a7c247740913
Revises: 65d4d21751c8
Create Date: 2024-12-08 15:54:11.333191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a7c247740913'
down_revision: Union[str, None] = '65d4d21751c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('size', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
