"""Deleted foreign key(location) in user table

Revision ID: e7cfe6a498a2
Revises: 5641bec18bc1
Create Date: 2024-12-08 16:00:39.400235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e7cfe6a498a2'
down_revision: Union[str, None] = '5641bec18bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.drop_column('users', 'location_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_ibfk_2', 'users', 'locations', ['location_id'], ['location_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
